#!/usr/bin/env python3
"""
embed-c2pa.py
=============
Embeds a C2PA (Coalition for Content Provenance and Authenticity) manifest
into an AI-generated marketing asset (image / video / audio / PDF) so the
asset carries a machine-readable provenance trail and a visible AI-generation
claim. This is the technical mechanism for EU AI Act Article 50 compliance
(applicable 2 Aug 2026) and aligns with the broader Content Authenticity
Initiative (CAI) standard.

Usage:
    python3 embed-c2pa.py \
        --input path/to/asset.png \
        --output path/to/signed-asset.png \
        --brand "Acme Corp" \
        --generator "Vertex AI / Nano Banana Pro" \
        --ai-claim "ai-generated-content" \
        --created 2026-05-16T10:30:00Z \
        [--prompt "the prompt used"] \
        [--reviewer "Jane Smith"] \
        [--signing-cert /path/to/cert.pem --signing-key /path/to/key.pem]

If c2pa-python is not installed, it is auto-installed via pip. If a real
signing certificate is not provided, the script falls back to a self-signed
test certificate (for development only — production use must supply a real
certificate from a CAI-recognized authority).

AI claim values:
    ai-generated-content        # Asset fully generated by AI
    ai-assisted-edits           # Human-created + AI-edited
    ai-no-substantive-changes   # AI used but no semantic change

The resulting asset can be inspected at https://contentcredentials.org/verify
or with any C2PA-aware viewer (Photoshop, Lightroom, Truepic, etc.).

Exit codes:
    0  success
    2  c2pa-python install failed
    3  unsupported asset format
    4  signing failure
    5  invalid arguments
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


SUPPORTED_FORMATS = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
    ".gif": "image/gif",
    ".tiff": "image/tiff",
    ".mp4": "video/mp4",
    ".mov": "video/quicktime",
    ".webm": "video/webm",
    ".mp3": "audio/mpeg",
    ".wav": "audio/wav",
    ".pdf": "application/pdf",
}

VALID_AI_CLAIMS = {
    "ai-generated-content",
    "ai-assisted-edits",
    "ai-no-substantive-changes",
}


def ensure_c2pa():
    """Install c2pa-python if missing. Returns the module."""
    try:
        import c2pa
        return c2pa
    except ImportError:
        pass
    print("Installing c2pa-python...", file=sys.stderr)
    try:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "--quiet", "c2pa-python>=0.5.0"]
        )
        import c2pa
        return c2pa
    except Exception as exc:
        print(f"ERROR: could not install c2pa-python: {exc}", file=sys.stderr)
        print(
            "Install manually: pip install c2pa-python>=0.5.0\n"
            "Docs: https://opensource.contentauthenticity.org/docs/python/",
            file=sys.stderr,
        )
        sys.exit(2)


def build_manifest(brand, generator, ai_claim, created, prompt, reviewer, asset_format):
    """Build a C2PA manifest dictionary per the v1.3 spec."""
    actions = [
        {
            "action": "c2pa.created",
            "when": created,
            "softwareAgent": {
                "name": generator,
                "version": "1.0",
            },
            "digitalSourceType": {
                "ai-generated-content": "http://cv.iptc.org/newscodes/digitalsourcetype/algorithmicMedia",
                "ai-assisted-edits":   "http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia",
                "ai-no-substantive-changes": "http://cv.iptc.org/newscodes/digitalsourcetype/minorHumanEdits",
            }[ai_claim],
        }
    ]
    if prompt:
        actions.append({
            "action": "c2pa.input.prompt",
            "when": created,
            "parameters": {"text": prompt},
        })
    if reviewer:
        actions.append({
            "action": "c2pa.reviewed",
            "when": datetime.now(timezone.utc).isoformat(),
            "reviewer": {"name": reviewer},
        })

    manifest = {
        "claim_generator": f"DigitalMarketingPro/3.4.0 ({generator})",
        "title": f"{brand} — AI-generated marketing asset",
        "format": SUPPORTED_FORMATS[asset_format],
        "instance_id": f"xmp:iid:dmp-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}",
        "assertions": [
            {
                "label": "c2pa.actions",
                "data": {"actions": actions},
            },
            {
                "label": "stds.schema-org.CreativeWork",
                "data": {
                    "@context": "https://schema.org",
                    "@type": "CreativeWork",
                    "author": [{"@type": "Organization", "name": brand}],
                    "dateCreated": created,
                },
            },
        ],
    }
    return manifest


def generate_self_signed_cert(tmp_dir):
    """Generate a self-signed cert for DEV use only. Returns (cert_path, key_path)."""
    from cryptography import x509
    from cryptography.x509.oid import NameOID
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import ec
    from datetime import timedelta

    key = ec.generate_private_key(ec.SECP256R1())
    subject = issuer = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, "DMP Dev Self-Signed C2PA"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Digital Marketing Pro"),
    ])
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(datetime.now(timezone.utc))
        .not_valid_after(datetime.now(timezone.utc) + timedelta(days=90))
        .sign(key, hashes.SHA256())
    )
    cert_path = Path(tmp_dir) / "dev-c2pa-cert.pem"
    key_path = Path(tmp_dir) / "dev-c2pa-key.pem"
    cert_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))
    key_path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    return str(cert_path), str(key_path)


def main():
    parser = argparse.ArgumentParser(description="Embed a C2PA provenance manifest in an AI-generated marketing asset.")
    parser.add_argument("--input", required=True, help="Source asset path")
    parser.add_argument("--output", required=True, help="Output asset path (with manifest embedded)")
    parser.add_argument("--brand", required=True, help="Brand name (becomes CreativeWork.author)")
    parser.add_argument("--generator", required=True, help='Generator name, e.g. "Vertex AI / Nano Banana Pro" or "Runway Gen-4"')
    parser.add_argument(
        "--ai-claim",
        default="ai-generated-content",
        choices=sorted(VALID_AI_CLAIMS),
        help="IPTC digital source type",
    )
    parser.add_argument("--created", help="ISO-8601 creation timestamp (default: now)")
    parser.add_argument("--prompt", help="Original generation prompt (optional, embedded as c2pa.input.prompt assertion)")
    parser.add_argument("--reviewer", help="Human reviewer name (optional, embedded as c2pa.reviewed assertion)")
    parser.add_argument("--signing-cert", help="PEM signing certificate; if omitted, a 90-day self-signed dev cert is generated")
    parser.add_argument("--signing-key", help="PEM signing key (must accompany --signing-cert)")
    args = parser.parse_args()

    in_path = Path(args.input)
    out_path = Path(args.output)

    if not in_path.exists():
        print(f"ERROR: input not found: {in_path}", file=sys.stderr)
        sys.exit(5)

    ext = in_path.suffix.lower()
    if ext not in SUPPORTED_FORMATS:
        print(f"ERROR: unsupported format {ext}. Supported: {sorted(SUPPORTED_FORMATS)}", file=sys.stderr)
        sys.exit(3)

    created = args.created or datetime.now(timezone.utc).isoformat()
    manifest = build_manifest(args.brand, args.generator, args.ai_claim, created, args.prompt, args.reviewer, ext)

    c2pa = ensure_c2pa()

    cert_path, key_path = args.signing_cert, args.signing_key
    using_dev_cert = False
    if not (cert_path and key_path):
        import tempfile
        tmpdir = tempfile.mkdtemp(prefix="dmp-c2pa-")
        try:
            cert_path, key_path = generate_self_signed_cert(tmpdir)
            using_dev_cert = True
        except ImportError:
            print("ERROR: cryptography package required for self-signed cert. Install: pip install cryptography", file=sys.stderr)
            sys.exit(4)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        # c2pa-python API: Builder for manifests, Signer for signing
        # The exact API surface varies by version; this handles 0.5.x and 0.6.x
        if hasattr(c2pa, "Builder"):
            builder = c2pa.Builder(json.dumps(manifest))
            signer = c2pa.create_signer(
                cert=open(cert_path, "rb").read(),
                key=open(key_path, "rb").read(),
                alg="es256",
                tsa_url="http://timestamp.digicert.com",
            )
            builder.sign_file(signer, str(in_path), str(out_path))
        else:
            # legacy single-call API
            c2pa.sign_file(
                source_path=str(in_path),
                dest_path=str(out_path),
                manifest=json.dumps(manifest),
                signer_info={
                    "alg": "es256",
                    "sign_cert": open(cert_path, "rb").read(),
                    "private_key": open(key_path, "rb").read(),
                    "ta_url": "http://timestamp.digicert.com",
                },
            )
    except Exception as exc:
        print(f"ERROR: C2PA signing failed: {exc}", file=sys.stderr)
        sys.exit(4)

    result = {
        "status": "success",
        "input": str(in_path),
        "output": str(out_path),
        "size_bytes": out_path.stat().st_size,
        "brand": args.brand,
        "generator": args.generator,
        "ai_claim": args.ai_claim,
        "created": created,
        "manifest_assertions": [a["label"] for a in manifest["assertions"]],
        "using_dev_cert": using_dev_cert,
        "verify_url": "https://contentcredentials.org/verify",
    }
    if using_dev_cert:
        result["warning"] = (
            "Signed with self-signed dev cert (90-day validity). "
            "PRODUCTION USE REQUIRES a real signing certificate from a CAI-recognized authority. "
            "See https://opensource.contentauthenticity.org/docs/manifest/signing-manifests/"
        )
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
